// CMMC 2.0 Compliance Data — KeeperPAM Mapping
// Domains, practices, and KeeperPAM module mappings

const KEEPER_MODULES = {
  kpm: "Keeper Password Manager",
  kcm: "Keeper Connection Manager",
  ksm: "Keeper Secrets Manager",
  kpam: "KeeperPAM Core",
  reporting: "Advanced Reporting & Alerts",
  sso: "SSO & Directory Integration",
};

const COVERAGE = {
  FULL: "full",
  PARTIAL: "partial",
  COMPLEMENTARY: "complementary",
};

// Each entry: { id, domain, domainCode, practiceId, description, level, modules[], coverage, guidance }
const CMMC_DATA = [

  // ─────────────────────────────────────────
  // ACCESS CONTROL (AC)
  // ─────────────────────────────────────────
  {
    id: 1,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L1-3.1.1",
    description: "Limit system access to authorized users, processes acting on behalf of authorized users, and devices (including other systems).",
    level: 1,
    modules: ["kpam", "sso", "kpm"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM enforces least-privilege access through role-based controls and vaulted credentials. SSO integration ensures only directory-authenticated users gain access. The Password Manager restricts credential exposure to authorized personnel only.",
  },
  {
    id: 2,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L1-3.1.2",
    description: "Limit system access to the types of transactions and functions that authorized users are permitted to execute.",
    level: 1,
    modules: ["kpam", "kcm"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM Core enforces granular permission sets per user role. Keeper Connection Manager further limits which systems and protocols (RDP, SSH, VNC) a user may access.",
  },
  {
    id: 3,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L1-3.1.20",
    description: "Verify and control/limit connections to external systems.",
    level: 1,
    modules: ["kcm", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Connection Manager provides a secure, audited gateway for all external system connections. No direct, unmonitored connections to privileged infrastructure are permitted.",
  },
  {
    id: 4,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L1-3.1.22",
    description: "Control CUI posted or processed on publicly accessible information systems.",
    level: 1,
    modules: ["kpm", "ksm"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper Password Manager and Secrets Manager ensure CUI-related credentials are never exposed in publicly accessible locations. Organizations must supplement with data classification controls.",
  },
  {
    id: 5,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.3",
    description: "Control the flow of CUI in accordance with approved authorizations.",
    level: 2,
    modules: ["kpam", "kcm", "reporting"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM enforces data flow controls through session isolation in Keeper Connection Manager. All privileged sessions are recorded and access to CUI systems is gated by workflow-based approvals.",
  },
  {
    id: 6,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.4",
    description: "Separate the duties of individuals to reduce the risk of malevolent activity.",
    level: 2,
    modules: ["kpam", "sso"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM supports separation of duties through dual-control approvals, split-knowledge workflows, and role segregation. Administrative roles are isolated and require separate authentication.",
  },
  {
    id: 7,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.5",
    description: "Employ the principle of least privilege, including for specific security functions and privileged accounts.",
    level: 2,
    modules: ["kpam", "kcm", "ksm"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM Core provides just-in-time (JIT) privilege elevation with time-bound sessions and automatic revocation. Secrets Manager rotates credentials after each use. Connection Manager restricts protocol access per user.",
  },
  {
    id: 8,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.6",
    description: "Use non-privileged accounts or roles when accessing non-security functions.",
    level: 2,
    modules: ["kpam", "sso"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM enforces privilege tiering — users operate under standard accounts by default and must explicitly request privilege elevation through an audited JIT workflow.",
  },
  {
    id: 9,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.7",
    description: "Prevent non-privileged users from executing privileged functions and audit the execution of such functions.",
    level: 2,
    modules: ["kpam", "reporting"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM blocks unauthorized privilege escalation attempts. Advanced Reporting captures all privilege function executions with timestamps, user context, and approval chain for audit trail.",
  },
  {
    id: 10,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.12",
    description: "Monitor and control remote access sessions.",
    level: 2,
    modules: ["kcm", "reporting"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Connection Manager provides full session recording, live monitoring, keystroke logging, and the ability to terminate suspicious sessions in real time. All session data is stored with tamper-evident logs.",
  },
  {
    id: 11,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.13",
    description: "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.",
    level: 2,
    modules: ["kcm", "kpm"],
    coverage: COVERAGE.FULL,
    guidance: "All Keeper Connection Manager tunnels use AES-256 encryption with TLS 1.2+ for remote sessions. Keeper Password Manager uses zero-knowledge encryption for credential storage and transmission.",
  },
  {
    id: 12,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.14",
    description: "Route remote access via managed access control points.",
    level: 2,
    modules: ["kcm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Connection Manager acts as the centralized, managed access control point for all privileged remote sessions — eliminating direct connections to sensitive infrastructure.",
  },
  {
    id: 13,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.15",
    description: "Authorize remote execution of privileged commands and access to security-relevant information via remote access only for documented operational needs.",
    level: 2,
    modules: ["kcm", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM requires documented request workflows before privileged remote commands are authorized. Connection Manager enforces these policies at the session gateway level.",
  },
  {
    id: 14,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L2-3.1.16",
    description: "Authorize wireless access prior to allowing connections.",
    level: 2,
    modules: ["sso"],
    coverage: COVERAGE.PARTIAL,
    guidance: "KeeperPAM's SSO integration supports network access control policies. Organizations must pair with NAC/WLAN solutions; KeeperPAM provides identity verification layer.",
  },
  {
    id: 15,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L3-3.1.2e",
    description: "Employ dual-authorization for access and execution of privileged accounts.",
    level: 3,
    modules: ["kpam"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM Core supports dual-authorization (two-person integrity) workflows for sensitive privileged operations, requiring approval from a second administrator before access is granted.",
  },

  // ─────────────────────────────────────────
  // IDENTIFICATION & AUTHENTICATION (IA)
  // ─────────────────────────────────────────
  {
    id: 16,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L1-3.5.1",
    description: "Identify information system users, processes acting on behalf of users, or devices.",
    level: 1,
    modules: ["sso", "kpm"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM's directory integration uniquely identifies every user and device. Password Manager enforces unique credentials per service account, eliminating shared passwords.",
  },
  {
    id: 17,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L1-3.5.2",
    description: "Authenticate (or verify) the identities of those users, processes, or devices, as a prerequisite to allowing access.",
    level: 1,
    modules: ["sso", "kpm", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "Multi-layer authentication through SSO federation, MFA enforcement in the Password Manager, and identity verification gates in KeeperPAM before any privileged access is granted.",
  },
  {
    id: 18,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.3",
    description: "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.",
    level: 2,
    modules: ["kpm", "sso", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper enforces MFA (TOTP, FIDO2/WebAuthn, Duo, SMS) for all vault access. SSO integration propagates MFA requirements. KeeperPAM requires MFA for all privileged session initiation.",
  },
  {
    id: 19,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.4",
    description: "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.",
    level: 2,
    modules: ["kpm", "sso"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper uses FIDO2/WebAuthn hardware keys and TOTP-based MFA that are inherently replay-resistant. Zero-knowledge architecture ensures authentication tokens cannot be harvested.",
  },
  {
    id: 20,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.5",
    description: "Employ identifier management with uniqueness requirements for service accounts.",
    level: 2,
    modules: ["kpm", "ksm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Secrets Manager maintains unique, rotated credentials for every service account and CI/CD pipeline. Password Manager enforces unique identifier policies across all stored credentials.",
  },
  {
    id: 21,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.6",
    description: "Disable identifiers after a defined period of inactivity.",
    level: 2,
    modules: ["sso", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "Directory sync through Keeper SSO integration automatically propagates account disabling from Active Directory/LDAP. KeeperPAM terminates sessions for inactive privileged accounts.",
  },
  {
    id: 22,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.7",
    description: "Enforce a minimum password complexity and change requirements.",
    level: 2,
    modules: ["kpm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Password Manager enforces configurable password complexity rules, minimum length requirements, and rotation schedules through centralized security policies.",
  },
  {
    id: 23,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.8",
    description: "Prohibit password reuse for a specified number of generations.",
    level: 2,
    modules: ["kpm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper's policy engine enforces password history rules, preventing reuse of previously used passwords based on configurable generation counts.",
  },
  {
    id: 24,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.10",
    description: "Store and transmit only cryptographically-protected passwords.",
    level: 2,
    modules: ["kpm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper's zero-knowledge, AES-256 encrypted vault ensures passwords are never transmitted or stored in plaintext. Client-side encryption means even Keeper employees cannot access stored credentials.",
  },
  {
    id: 25,
    domain: "Identification & Authentication",
    domainCode: "IA",
    practiceId: "IA.L2-3.5.11",
    description: "Obscure feedback of authentication information.",
    level: 2,
    modules: ["kpm", "kcm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Password Manager masks passwords in the UI and prevents shoulder-surfing. Connection Manager masks credentials injected into remote sessions, preventing credential exposure in session recordings.",
  },

  // ─────────────────────────────────────────
  // AUDIT & ACCOUNTABILITY (AU)
  // ─────────────────────────────────────────
  {
    id: 26,
    domain: "Audit & Accountability",
    domainCode: "AU",
    practiceId: "AU.L2-3.3.1",
    description: "Create and retain system audit logs and records to enable monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.",
    level: 2,
    modules: ["reporting", "kcm"],
    coverage: COVERAGE.FULL,
    guidance: "Advanced Reporting & Alerts maintains comprehensive, tamper-evident audit logs of all Keeper events. Connection Manager records full session video and keystroke logs. SIEM integration exports logs to external systems.",
  },
  {
    id: 27,
    domain: "Audit & Accountability",
    domainCode: "AU",
    practiceId: "AU.L2-3.3.2",
    description: "Ensure that the actions of individual users can be traced to those users so they can be held accountable for their actions.",
    level: 2,
    modules: ["reporting", "kcm", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "Every KeeperPAM action is tied to an authenticated user identity. Session recordings in Connection Manager create irrefutable audit trails linking actions to specific individuals.",
  },
  {
    id: 28,
    domain: "Audit & Accountability",
    domainCode: "AU",
    practiceId: "AU.L2-3.3.5",
    description: "Correlate audit record review, analysis, and reporting processes.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper's Advanced Reporting provides cross-system event correlation, customizable dashboards, scheduled reports, and integration with SIEM platforms (Splunk, Microsoft Sentinel, QRadar) for centralized analysis.",
  },
  {
    id: 29,
    domain: "Audit & Accountability",
    domainCode: "AU",
    practiceId: "AU.L2-3.3.6",
    description: "Provide system capability that compares and synchronizes internal clocks with an authoritative source.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper uses NTP-synchronized timestamps across all audit records. Organizations should ensure their NTP infrastructure is properly configured; Keeper's cloud infrastructure maintains accurate time sources.",
  },

  // ─────────────────────────────────────────
  // CONFIGURATION MANAGEMENT (CM)
  // ─────────────────────────────────────────
  {
    id: 30,
    domain: "Configuration Management",
    domainCode: "CM",
    practiceId: "CM.L2-3.4.1",
    description: "Establish and maintain baseline configurations and inventories of organizational systems.",
    level: 2,
    modules: ["ksm", "reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper Secrets Manager maintains configuration baselines for application credentials and service accounts. Organizations should supplement with dedicated CMDB solutions for full system inventory.",
  },
  {
    id: 31,
    domain: "Configuration Management",
    domainCode: "CM",
    practiceId: "CM.L2-3.4.2",
    description: "Establish and enforce security configuration settings for products employed in organizational systems.",
    level: 2,
    modules: ["kpm", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM's admin console enforces security configuration policies across all users and devices. Password Manager security policies are centrally managed and cannot be bypassed by end users.",
  },
  {
    id: 32,
    domain: "Configuration Management",
    domainCode: "CM",
    practiceId: "CM.L2-3.4.6",
    description: "Employ the principle of least functionality by configuring systems to provide only essential capabilities.",
    level: 2,
    modules: ["kpam", "kcm"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM enforces least functionality through granular permission sets — users can only access the systems and protocols they are explicitly authorized for. Connection Manager blocks unauthorized protocol usage.",
  },

  // ─────────────────────────────────────────
  // SYSTEM & COMMUNICATIONS PROTECTION (SC)
  // ─────────────────────────────────────────
  {
    id: 33,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L1-3.13.1",
    description: "Monitor, control, and protect communications at external boundaries and key internal boundaries.",
    level: 1,
    modules: ["kcm"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper Connection Manager controls all privileged communications at system boundaries. Organizations should supplement with network monitoring tools for full boundary protection.",
  },
  {
    id: 34,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L1-3.13.5",
    description: "Implement subnetworks for publicly accessible system components.",
    level: 1,
    modules: ["kcm"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Connection Manager supports deployment in DMZ configurations. Organizations should implement network segmentation; KeeperPAM provides the access control layer atop this architecture.",
  },
  {
    id: 35,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L2-3.13.3",
    description: "Separate user functionality from system management functionality.",
    level: 2,
    modules: ["kpam", "sso"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM enforces strict separation between standard user accounts and administrative accounts. Admin functions require separate authentication and are fully isolated in the KeeperPAM admin console.",
  },
  {
    id: 36,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L2-3.13.8",
    description: "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission.",
    level: 2,
    modules: ["kpm", "kcm", "ksm"],
    coverage: COVERAGE.FULL,
    guidance: "All Keeper data transmission uses AES-256 encryption with TLS 1.2+. Zero-knowledge architecture ensures end-to-end encryption even in transit through Keeper's cloud infrastructure.",
  },
  {
    id: 37,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L2-3.13.10",
    description: "Establish and manage cryptographic keys when cryptography is employed.",
    level: 2,
    modules: ["kpm", "ksm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper's zero-knowledge key management framework generates and manages encryption keys client-side. Secrets Manager handles application-level cryptographic key storage and rotation.",
  },
  {
    id: 38,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L2-3.13.15",
    description: "Protect the authenticity of communications sessions.",
    level: 2,
    modules: ["kcm", "kpm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Connection Manager uses session tokens with cryptographic binding to prevent session hijacking. Password Manager's zero-knowledge model ensures session authenticity from client to server.",
  },
  {
    id: 39,
    domain: "System & Communications Protection",
    domainCode: "SC",
    practiceId: "SC.L2-3.13.16",
    description: "Protect the confidentiality of CUI at rest.",
    level: 2,
    modules: ["kpm", "ksm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper stores all data with AES-256 encryption at rest. The zero-knowledge architecture ensures CUI-related credentials and secrets are encrypted before leaving the client device.",
  },

  // ─────────────────────────────────────────
  // SYSTEM & INFORMATION INTEGRITY (SI)
  // ─────────────────────────────────────────
  {
    id: 40,
    domain: "System & Information Integrity",
    domainCode: "SI",
    practiceId: "SI.L1-3.14.1",
    description: "Identify, report, and correct information and information system flaws in a timely manner.",
    level: 1,
    modules: ["reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Advanced Reporting provides alerting on anomalous access patterns and potential account compromises. Organizations should supplement with vulnerability management tools.",
  },
  {
    id: 41,
    domain: "System & Information Integrity",
    domainCode: "SI",
    practiceId: "SI.L2-3.14.6",
    description: "Monitor organizational systems including inbound and outbound communications traffic to detect attacks and indicators of potential attacks.",
    level: 2,
    modules: ["reporting", "kcm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper's Advanced Reporting provides anomaly detection and behavioral analytics on privileged access patterns. Connection Manager monitors all privileged session traffic for suspicious activity.",
  },
  {
    id: 42,
    domain: "System & Information Integrity",
    domainCode: "SI",
    practiceId: "SI.L2-3.14.7",
    description: "Identify unauthorized use of organizational systems.",
    level: 2,
    modules: ["reporting", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM detects and alerts on unauthorized access attempts, credential sharing violations, and anomalous privileged activity. Real-time alerts can be sent via email, SIEM, or webhook.",
  },

  // ─────────────────────────────────────────
  // INCIDENT RESPONSE (IR)
  // ─────────────────────────────────────────
  {
    id: 43,
    domain: "Incident Response",
    domainCode: "IR",
    practiceId: "IR.L2-3.6.1",
    description: "Establish an operational incident-handling capability that includes preparation, detection, analysis, containment, recovery, and user activities.",
    level: 2,
    modules: ["reporting", "kpam"],
    coverage: COVERAGE.PARTIAL,
    guidance: "KeeperPAM supports incident response with rapid credential rotation, session termination, and comprehensive audit logs for forensic analysis. Organizations should supplement with formal IR procedures.",
  },
  {
    id: 44,
    domain: "Incident Response",
    domainCode: "IR",
    practiceId: "IR.L2-3.6.2",
    description: "Track, document, and report incidents to officials and/or authorities.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.FULL,
    guidance: "Advanced Reporting provides incident documentation with complete event timelines, user attribution, and exportable reports in formats suitable for regulatory reporting.",
  },

  // ─────────────────────────────────────────
  // RISK ASSESSMENT (RA)
  // ─────────────────────────────────────────
  {
    id: 45,
    domain: "Risk Assessment",
    domainCode: "RA",
    practiceId: "RA.L2-3.11.1",
    description: "Periodically assess the risk to organizational operations, assets, and individuals.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper's reporting module provides privileged access risk insights and credential security scores. Organizations should use formal risk assessment methodologies; Keeper provides supporting data.",
  },
  {
    id: 46,
    domain: "Risk Assessment",
    domainCode: "RA",
    practiceId: "RA.L2-3.11.2",
    description: "Scan for vulnerabilities in organizational systems and applications periodically.",
    level: 2,
    modules: ["ksm", "reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper Secrets Manager eliminates hardcoded credentials that are common vulnerability sources. Reporting provides visibility into weak or reused credentials. Pair with dedicated vulnerability scanners.",
  },

  // ─────────────────────────────────────────
  // PERSONNEL SECURITY (PS)
  // ─────────────────────────────────────────
  {
    id: 47,
    domain: "Personnel Security",
    domainCode: "PS",
    practiceId: "PS.L2-3.9.2",
    description: "Ensure that CUI is protected during and after personnel actions such as terminations and transfers.",
    level: 2,
    modules: ["kpam", "sso", "kpm"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM's directory sync immediately revokes access when an employee is terminated. Credentials in shared vaults are auto-rotated. All privileged sessions are terminated upon deprovisioning.",
  },

  // ─────────────────────────────────────────
  // MEDIA PROTECTION (MP)
  // ─────────────────────────────────────────
  {
    id: 48,
    domain: "Media Protection",
    domainCode: "MP",
    practiceId: "MP.L2-3.8.6",
    description: "Implement cryptographic mechanisms to protect the confidentiality of CUI during transport.",
    level: 2,
    modules: ["kpm", "ksm"],
    coverage: COVERAGE.FULL,
    guidance: "All Keeper data exports and shares use end-to-end encryption. Secrets Manager enforces encrypted transmission for all secrets delivery to applications and pipelines.",
  },

  // ─────────────────────────────────────────
  // SECURITY ASSESSMENT (CA)
  // ─────────────────────────────────────────
  {
    id: 49,
    domain: "Security Assessment",
    domainCode: "CA",
    practiceId: "CA.L2-3.12.1",
    description: "Periodically assess security controls to determine if they are effective.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper's Advanced Reporting provides assessment-ready compliance reports, access reviews, and security posture metrics. Reports can be scheduled and exported for C3PAO assessors.",
  },
  {
    id: 50,
    domain: "Security Assessment",
    domainCode: "CA",
    practiceId: "CA.L2-3.12.4",
    description: "Develop, document, and periodically update system security plans.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "KeeperPAM documentation and reporting exports support SSP development. Organizations should use dedicated GRC tools for full system security plan management.",
  },

  // ─────────────────────────────────────────
  // MAINTENANCE (MA)
  // ─────────────────────────────────────────
  {
    id: 51,
    domain: "Maintenance",
    domainCode: "MA",
    practiceId: "MA.L2-3.7.5",
    description: "Require MFA to establish nonlocal maintenance sessions and terminate such connections when maintenance is complete.",
    level: 2,
    modules: ["kcm", "kpm"],
    coverage: COVERAGE.FULL,
    guidance: "Keeper Connection Manager enforces MFA for all remote maintenance sessions and automatically terminates sessions after configurable inactivity or time limits. All maintenance sessions are recorded.",
  },

  // ─────────────────────────────────────────
  // AWARENESS & TRAINING (AT)
  // ─────────────────────────────────────────
  {
    id: 52,
    domain: "Awareness & Training",
    domainCode: "AT",
    practiceId: "AT.L2-3.2.2",
    description: "Ensure that personnel are aware of the security risks associated with their activities.",
    level: 2,
    modules: ["reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper's reporting provides security risk visibility and can generate user-level reports on risky behaviors (weak passwords, credential reuse). Organizations should supplement with formal security awareness training programs.",
  },

  // ─────────────────────────────────────────
  // LEVEL 3 ADVANCED PRACTICES
  // ─────────────────────────────────────────
  {
    id: 53,
    domain: "Access Control",
    domainCode: "AC",
    practiceId: "AC.L3-3.1.3e",
    description: "Employ secure information transfer solutions to control information flows between security domains.",
    level: 3,
    modules: ["kcm", "kpam"],
    coverage: COVERAGE.FULL,
    guidance: "KeeperPAM implements zero-trust architecture for cross-domain information flows. Connection Manager enforces protocol-level isolation between security domains.",
  },
  {
    id: 54,
    domain: "System & Information Integrity",
    domainCode: "SI",
    practiceId: "SI.L3-3.14.1e",
    description: "Use threat intelligence to inform the development of the system and security architecture.",
    level: 3,
    modules: ["reporting"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper's SIEM integration allows threat intelligence feeds to be correlated with privileged access events. Organizations should integrate Keeper with a SIEM/SOAR platform for full threat-informed defense.",
  },
  {
    id: 55,
    domain: "Risk Assessment",
    domainCode: "RA",
    practiceId: "RA.L3-3.11.1e",
    description: "Employ a cyber threat hunting program to search for indicators of compromise in organizational systems.",
    level: 3,
    modules: ["reporting", "kcm"],
    coverage: COVERAGE.PARTIAL,
    guidance: "Keeper session recordings and behavioral analytics support threat hunting for privileged account abuse. Integrate with SOAR tools for automated threat hunting workflows.",
  },
];

// Domain metadata for accordion display
const DOMAINS = [
  {
    code: "AC",
    name: "Access Control",
    description: "Control access to CUI and organizational systems through authentication, authorization, and least-privilege principles.",
    icon: "🔐",
    color: "#0057FF",
  },
  {
    code: "IA",
    name: "Identification & Authentication",
    description: "Ensure users and devices are uniquely identified and authenticated before accessing systems containing CUI.",
    icon: "🪪",
    color: "#7C3AED",
  },
  {
    code: "AU",
    name: "Audit & Accountability",
    description: "Create, protect, and retain audit records to enable monitoring, analysis, and investigation of unauthorized activity.",
    icon: "📋",
    color: "#059669",
  },
  {
    code: "CM",
    name: "Configuration Management",
    description: "Establish and maintain baseline configurations and security settings for systems containing CUI.",
    icon: "⚙️",
    color: "#D97706",
  },
  {
    code: "SC",
    name: "System & Communications Protection",
    description: "Monitor, control, and protect CUI in transit and at rest through cryptographic and architectural controls.",
    icon: "🌐",
    color: "#DC2626",
  },
  {
    code: "SI",
    name: "System & Information Integrity",
    description: "Identify and protect against malicious code, and monitor systems to detect attacks and unauthorized use.",
    icon: "🛡️",
    color: "#0891B2",
  },
  {
    code: "IR",
    name: "Incident Response",
    description: "Establish capabilities to prepare for, detect, contain, and recover from cybersecurity incidents.",
    icon: "🚨",
    color: "#E11D48",
  },
  {
    code: "RA",
    name: "Risk Assessment",
    description: "Periodically assess risk to organizational operations and systems and scan for vulnerabilities.",
    icon: "📊",
    color: "#7C3AED",
  },
  {
    code: "PS",
    name: "Personnel Security",
    description: "Screen individuals prior to access and ensure CUI is protected when personnel actions occur.",
    icon: "👤",
    color: "#0D9488",
  },
  {
    code: "MP",
    name: "Media Protection",
    description: "Protect and sanitize system media containing CUI, both paper and digital.",
    icon: "💾",
    color: "#4338CA",
  },
  {
    code: "CA",
    name: "Security Assessment",
    description: "Periodically assess controls, develop and maintain system security plans, and manage POA&Ms.",
    icon: "✅",
    color: "#15803D",
  },
  {
    code: "MA",
    name: "Maintenance",
    description: "Perform maintenance on organizational systems and control maintenance tools and remote access.",
    icon: "🔧",
    color: "#B45309",
  },
  {
    code: "AT",
    name: "Awareness & Training",
    description: "Ensure personnel are aware of security risks and trained to perform security responsibilities.",
    icon: "📚",
    color: "#BE185D",
  },
];
